#
# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: Apache-2.0 OR GPL-3.0-only
#
---

- name: add insecure registries to docker daemon
  template:
    src=docker.service.j2
    dest=/lib/systemd/system/docker.service
    owner=root
    group=root
  notify:
    - reload unit files
    - restart docker
