#
#  Copyright 2015 VMware, Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
---

# in ansible 2.1 this will work
- name: Add photon repository
  yum_repository:
   name: photon repo
   description: photon repo
   baseurl: "{{ photon_yum_repo }}"
   enabled: "{{ photon_yum_repo_enabled }}"

- name: ensure yum is installed
  command: bash -c "rpm -q yum || tdnf install -y yum" creates=/usr/bin/yum

# - name: Update default Photon packages to latest
#   command: tdnf -y distro-sync

- name: add additional packages
  yum: name={{ item }} state=present
  with_items: "{{ photon_packages }}"

- name: update systemd to fix network daemon crashes
  yum: name=systemd state=present
